### ISSUE TITLE
Interactive Graph Unclear

### ISSUE THREAD

**Issue by GrimReaper2654** [EddieTheEd/obsidiannotes-v.3#4]
**Describe the bug**
The interactive graph is very hard to read
<img width="741" alt="Screenshot 2023-03-22 at 9 28 25 am" src="https://user-images.githubusercontent.com/80506189/226778386-f7bdf668-88bd-4545-9171-fc41a16f138b.png">

**To Reproduce**
1. look at the interactive graph on the website
2. See something so hideous that it must be fixed

**Expected behavior**
The graph should be clear and easy to read.

**Comment by EddieTheEd** [comment]
1. get glasses
2. its called suffering from success, its a global graph what do you expect + you can zoom in and hover over the nodes to see the names
3. who uses graphs for navigation you silly fool
